# -*- coding: utf-8 -*-
# """day_1.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1bWIiD0B9n_XpOR78NCpOE3tLKF_z2YyL

# # Python basics commands with notes 

# ---
# """

a = "Hello World from Pakistan"
print(a) #print() : a function we use for print values on console

print("Type : " , type(a)) #finding type of variable a using type() func
print("Length : " , len(a)) #finding length of variable a using len() func

# exploring type func with different arguments
a = "Hello World"
print(a , " : " , type(a) )
a = 3
print(a , " : " , type(a) )
a = 4.8
print(a , " : " , type(a) )
a = True
print(a , " : " , type(a) )
a = ["Hello","world",2012,False]
print(a , " : " , type(a) )
a = ("Hello","world")
print(a , " : " , type(a) )
a = {1,2,3,4,5}
print(a , " : " , type(a) )
a = {"Firstname":"Kashif","Lastname":"Shaikh",}
print(a , " : " , type(a) )
#check out types of all the values in result

#single assignment
a = 12
b = 3
print("Single assignment")
print("a = ",a)
print("b = ",b)
#multiple assignment
a , b = 12,3
print("Multiple assignment")
print("a = ",a)
print("b = ",b)

#exploring list and list methods
# List is just like as array, but in arrays we only take all elements of single data type, but in list you take any datatype value on every single index
list1 = ["Hello" , False , 2012 , 33.0] #in this list, we take all the datatypes value on every single index
#you can access every single index value using their index value just like list1[0]
print("0 index value : " , list1[0])
print("2 index value : " , list1[2])

#adding new element to list
list1 = ["Hello" , False , 2012 , 33.0]
print("old list : ",list1)
list1.append("New element 1") # append function take a new element and merge in the last of old list
print("after appending element : ",list1)

#removing very last element from list
list1 = ["Hello" , False , 2012 , 33.0]
print("before removing element : ",list1)
list1.pop() # pop() , this function removes element from the last of the list 
print("after removing element : ",list1)

#removing a particular index element from list
list1 = ["Hello" , False , 2012 , 33.0]
print("before removing element : ",list1)
list1.pop(1) # pop() , this function also takes 1 argument and the argument was index of particular element
print("after removing element : ",list1)

#updating list
list1 = ["Hello" , False , 2012 , 33.0]
print("before updating elements : ",list1)
list1[0] = "World"
list1[1] = True
print("after updating elements : ",list1)

#casting - change datatypes of data
a = 5 
changeIntoString = str(a) #str() function take 1 argument and change the argument into string type // "5"
print(type(changeIntoString)," = ",changeIntoString)
changeIntoInteger = int(a) #int() function take 1 argument and change the argument into integer type // 5
print(type(changeIntoInteger)," = ",changeIntoInteger)
changeIntoFloat = float(a) #float() function take 1 argument and change the argument into float type // 5.0
print(type(changeIntoFloat)," = ",changeIntoFloat)

#taking input from user
a = input()
print(a)
# input() function use to take input from user and store into the variable that place on left side of input
# input("Enter value : ") , this func also takes the msg in argument that you want to print to show user
a = input("Enter value : ")
print(a," = ",type(a))
# but all the value that enter by users are in string type you can convert using cast into your desired type
a = int(input("Enter value : "))
print(a," = ",type(a))
# you also use this way
a = input("Enter value : ")
a = int(a)
print(a," = ",type(a))